# investment_club/models/__init__.py
from . import investment_club
from . import investment_project
from . import membership
from . import membership_renewal
from . import investment_subscription
from . import actual_return
from . import contact
from . import crm_lead
from . import res_config_settings
from . import contact_codes
from . import account_move
from . import account_payment_inherit
from . import sale_contract_inherit
from . import investment_actual_return_inherit
from . import investment_project_inherit
from . import investment_reject_wizard
from . import membership_terminate_wizard
from . import subscription_terminate_wizard
from . import investor_death_wizard
